name = "GWSC"
uuid = "13605eb4-7e26-11e9-1115-f51d9e886ef4"
authors = ["Zu-Cheng Chen"]
version = "0.1.0"

[compat]
julia = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
